### ISSUE TITLE
Name of the project

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#1]
This question has been asked many times. @hgrecco and myself had chosen to keep Lantz but with more people involved it makes sense to ask it again.
I like Lantz but if we go that we should still start from a bare repo for the core part I think.

**Comment by hgrecco** [comment]
I obviously like Lantz a well. As I explained in the docs it has a deep meaning to me. In more practical terms, I also think Lantz is one of the few multilayered toolkits for instrumentation in python and it has a history. 

I think I have shown my commitment to make Lantz a community project when I transferred it (not just forked) it to LabPy. I hope that others see this as well. And therefore I hope that as soon as you start contributing, you call this **our** project. I have no problem at all with that.

**Comment by arsenovic** [comment]
a good project  name is unique, pronounceable,  and easy to import. lantz is all, and i dont have any libraries of my own, so i like it!

(although keep in mind that  some americans might hear the name and go home to  google `lance`!)

**Comment by MatthieuDartiailh** [comment]
@alexforencich what is your opinion ? It seemed to matter to you in the previous discussion in the python-ivi thread.

**Comment by alexforencich** [comment]
Well, I think the main point is to start with a clean repo so we can build without worrying about any legacy constraints.  To that end, it may be sensible to change the name as it will likely not be backwards compatible with whatever previously held that name.  I suppose we could stick with the name Lantz if everyone is OK with that.  Alternatively, the group is called LabPy, so we could also go with that.

**Comment by MatthieuDartiailh** [comment]
I think labpy is a bit too general for an instrumentation toolkit. I tried to ping some of the people who took part in the discussion on the python-ivi thread to get more feedbacks. If nobody ends up strongly against Lantz, I would say we keep it but we re-start from a clean lantz_core repo. @hgrecco does it make sense and agrees with you ?

**Comment by hgrecco** [comment]
I am fine with keeping the name and starting a clean repo.

**Comment by arsenovic** [comment]
i appreciate @alexforencich's concern, but i agree that `labpy` is too general (also its `pylab` backwards, which is a different thing). here are some ideas
- `pinst` (python for instruments [probably too close to pint])
- `scikit-vi` (scikit for virtual instruments [imported as `skivi`])
- `vipy` ( virtual instruments in python)

but i reckon if   @hgrecco    doesnt mind breaking Lantz's projects backwards compatibility, i say lets keep it simple.

**Comment by hgrecco** [comment]
Some of my users, only instantiate the existing drivers. For them, I will provide a clean upgrade path.

Of course, many other users build and contribute new drivers. They will need to relearn a few things but the benefits are worth it. 

Let's move forward!

**Comment by MatthieuDartiailh** [comment]
@hgrecco as we agreed to start from a clean repo I will probably delete and re-create lantz_core later in the week, is that ok ?

**Comment by hgrecco** [comment]
@MatthieuDartiailh Yes. I was waiting until the name of project to settle. So go ahead.

**Comment by MatthieuDartiailh** [comment]
We all agreed to that so I am closing.
