### ISSUE TITLE
Range/Limits handling in Feature

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#10]
The question here is how : do we handle Feature which can have a variable allowed range/limits (ie minimum, maximum, step I will only use limits in the following) ?
For static ones we can simply pass a tuple of length 3 (or 2 if step does not apply .... not sure it is ever the case) and generate a kind of validator from there.
As limits behavior can depend on multiple Features, in Eapii there are not tied to any specific Feature but simply declared by creating a getter method whose name starts with _range_*. Feature can then reference the name in their 'limits' kwarg. The getter method is actually called once and the validator in then cached and the HasFeatures base class provides a method to clear this cache. We could or course support doing this through the Feature 'discard' kwarg.

**Comment by hgrecco** [comment]
I think that using a named getter method is a good idea. And it would be good to provide a way to invalidate the cache. A common case is as following (The syntax is just an example):

``` python
@Feature(limits='current_limit')
def current(self):
    return self.query('CURRENT?')

@current.setter
def current(self, value):
   self.query('CURRENT {.3f}'.format(value))


@Feature(limits='current_limit')
def current_limit(self):
    return self.query('CURRENT LIMIT?')

@current.setter
def current_limit(self, value):
   self.query('CURRENT LIMIT {.3f}'.format(value))
   # HERE YOU WANT TO INVALIDATE THE VALUE OF LIMITS CACHED IN CURRENT
   # Maybe it can be done automatically if current_limit provides a setter.
```

**Comment by MatthieuDartiailh** [comment]
What I have in mind is a bit different because there is in general no direct way to deduce the limits from the range set on the instrument, so we need to build the validator. My code would look a bit more like :  

``` python

current = Feature('CURRENT?', 'CURRENT {.3f}', limits='current_limit')

# The limits keyword could also hold a dict {'limits': 'current_limit'} to specify 
# we want to discard the limits cache and not the Feature cache.
current_range = Feature('CURRENT LIMIT?', 'CURRENT LIMIT {}', discard='current_limit')

def _limits_current_limit(self):
    if self.current_range == '100 mA':
         # Note that the instrument supports 20% more than the name of the selected 
         # range suggests.
         return FloatValidator(-120, 120, 1, unit='mA')
     else:
         return FloatValidator(-12, 12, 0.1, unit='mA')
```

The FloatValidator holding the machinery to check that the value passed to current respect the min, max and step.

**Comment by hgrecco** [comment]
sounds good to me.

**Comment by MatthieuDartiailh** [comment]
Would you agree on the dictionary for discard (it will make it much easier to implement) ?

**Comment by hgrecco** [comment]
yes. go for it.

**Comment by MatthieuDartiailh** [comment]
As this is pretty straightforward and inherited directly from Eapii I will wait for more feedback and for my other PRs to be merged before doing it.

**Comment by MatthieuDartiailh** [comment]
This is implemented in https://github.com/LabPy/lantz_core/pull/4.
