### ISSUE TITLE
Drop Python 3.2 support

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#13]
Testing another library I work on, I discovered that future is not compatible with python 3.2 because of some oddities in how this particular version handles strings, bytes and stuff. It works however perfectly fine with 3.3 and 3.4.
This is something future won't fix because it would be too messy to do. So either we drop python 3.2 (which in my opinion is really no big deal) or we deal with the compatibilty mess.

**Comment by hgrecco** [comment]
I have not seen anybody that need to stay into 3.2. In fact, I asked in the lantz list a few months ago and in all the answers (public and private) people said that they see no problem in moving to the latest 3.X series. So I am fine in dropping 3.2

**Comment by enkore** [comment]
Except for Debian stable (guh!) and the old Ubuntu LTS no mainstream distro ships Python 3.2 anyway

**Comment by crazyfermions** [comment]
+1 for dropping P3.2.

**Comment by hgrecco** [comment]
@enkore Is true, but thanks to anaconda and similar distros is really trivial (an many times a good idea) to have a self contained and independent python distro independent of the system python. It takes more space but makes things easier to maintain and distribute.

**Comment by MatthieuDartiailh** [comment]
Ok good to know. I will close on monday if nobody else comment and update the wiki.

**Comment by MatthieuDartiailh** [comment]
Closing as nobody oposed. We won't support python 3.2.
