### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by alexforencich** [LabPy/labpy-discussion#17]
I think we need to figure out some conventions on how to organize and name files for the drivers.  I am presuming that we will organize drivers by manufacturer, as this seems to be the most sensible method.  

For common base classes that are used by multiple drivers, I suggest storing these in a folder called 'common'.  I think the driver dev branch has 'standards' right now, but that to me indicates something along the lines of calibration standards or something along those lines and not driver components.  Thoughts?

For individual drivers, there is a strong possibility that model numbers will start with numbers, which is not allowed for a file name.  So, what is the sensible solution in this case?  In python-ivi, I duplicated the manufacturer name.  I suppose this makes things a little verbose, but I think it makes the most sense and it's unambiguous.  Another option might be adding a standard prefix, perhaps model_.  

For manufacturers that have changed names multiple times (i.e. HP/Agilent/Keysight/???) what makes the most sense?  Put everything under the most recent name (i.e. keysight)?  Put instrments under the faceplate name (hp for the really old stuff, agilent for most things, keysight for new stuff)?  Something else?

**Comment by MatthieuDartiailh** [comment]
We already have an issue in lantz_driver about this. I think we agreed about the vendor stuff and aliasing instrument as necessary for hp/agilent/keysight.

**Comment by alexforencich** [comment]
Sigh, this is the problem with not having a single unified discussion board....issue is here: https://github.com/LabPy/lantz_drivers/issues/1

**Comment by MatthieuDartiailh** [comment]
Sorry for that.

**Comment by alexforencich** [comment]
That's alright, I completely forgot about that.  I do remember discussing it, I just didn't check the right issue page.
