### ISSUE TITLE
Hierarchical drivers

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#2]
This has already been discussed in https://github.com/LabPy/lantz/issues/46#issuecomment-74355868. I will just repeat my post proposing an implementation here.

**Comment by MatthieuDartiailh** [comment]
Hi, 
So I got a chance to write a possible subsystems implementation. It tried to make few hypothesis on what we will decide for other part of the code. As this is still WIP and that there are still some Eapii concept hanging around I won't directly open a PR (you can always look at the code in my repo of lantz_core, mostly has_features.py), but I will describe what it can do so that we see whether or not it fits our needs. Please comment ! (@p3trus, @arsenovic feel free to join the discussion)

Let's start with some code that would be valid in that implementation : 

``` python
from lantz_core.has_features import subsystem, set_feat, channel
from lantz_core.base_instrument import BaseInstrument
from lantz_core.features.feature import Feature


class GenericLockIn(BaseInstrument):
    """
    """
    #: Mode of acquisition of the lock-in
    acquisition_mode = Feature()

    #: Oscillator subsystem
    oscillator = subsystem()
    with oscillator as o:

        #: Amplitude of the oscillator in V.
        o.amplitude = Feature()

        #: Frequency of the oscillator in Hz
        o.frequency = Feature(getter=True)

        @o()
        def _get_frequency(self, feature):
            return feature

    channels = channel('list_channels')
    with channels as c:
        c.x = Feature()

    def list_channels(self):
        return 1, 2, 3


class SpecialisedLockIn(GenericLockIn):
    """
    """
    oscillator = subsystem()
    with oscillator as o:
        o.frequency = set_feat(secure_comm=2)

        @o()
        def _get_frequency(self, feature):
            return self
```

So let me explain what goes on here. The idea is to create a generic lock-in driver in which the parameters of the internal oscillator make a subsytem (and which has several acquisition channels, but that is just to show how channels might work). I assumed we were going to use some kind of descriptor similar to Lantz Feature or Eapii IProperty. 

In GenericLockIn : 
- first we create the acquisition_mode property (without any arguments as we have not discussed that yet) with a comment starting with #: which is recognized by sphinx as documentation which will be used to build the docstring of the descriptor. 
- then we declare a subsytem named oscillator. The subsystem object will be used by the metaclass to create a custom subclass of SubSystem fitting our needs. Here we do not specify any base class but we could to get some previously declared behavior, actually we can specify several and take benefits of using mixins. Note that here also the comment will be used as docstring. Now we add some features to our system. As the name oscillator is a bit long we use a context manager to get a short alias. We can now add features to our subsystem and use Eapii customization hooks (if we keep them) to define a special behavior (note the decorator to attach the method to the subsystem, this allows to avoid naming conflicts, actually I don't think we need a decorator with args so we could remove the ()). 
- finally we add a channel declaration, which takes as argument the name of the method used to list the available channels (should return a list of their ids). And we can proceed just like for subsystem for the features and methods.
  NB : We could of course go deeper in the nesting of subsystems and channels.

When you instantiate a generic lock-in, one instance of each subsystem is created and the channel attribute is given a ChannelContainer (channel.py) which behaves like an iterable and can be used to access to channel by id.

Now lets say you want to customize the frequency of the oscillator. You subclass the GenericLockIn, declare the subsystem oscillator and change the feature behavior either using the set_feat object which allow you to change any argument of the feature or by creating a new get method (or both). The metaclass takes care for you of subclassing the GenericLockInOscillator class (created by the metaclass when creating GenericLockIn) and can possibly add new mixin classes if you need to, and of customizing the features.

Old eapii ways to declare a SubSystem (Channel) by directly passing a class as class attribute are still supported but do not make sense anymore.

This implementation, it seems to me, solves a number of the issues related to the implementation of hierarchical drivers we mentioned in the labpy-discussion wiki, while still allowing to use descriptor and avoiding to override getattr or setattr. The drawback being a longer class creation time and hence importing but that need to happen only once in each application, and also a more complex codebase but nothing we can deal with (even if a strong testsuite will be imperative). **Once things I like a lot also is that the hierarchy of the declaration reflects the hierarchy of the driver**. I am open to suggestion remarks and comments, and I would prefer to have some feedback before cleaning the code a bit and writing a full testsuite (the example does work with the current implementation).

**Comment by hgrecco** [comment]
Just to repeat my opinion here
+1 on hierarchy
+1 on the syntax using context managers

**Comment by arsenovic** [comment]
this post made my brain explode. ill have to read it a few times and get back to you.

**Comment by MatthieuDartiailh** [comment]
Take your time. Did you find the code, by the way ? Not sure it will help as this is fairly dark metaclass magic but perhaps it will.

**Comment by MatthieuDartiailh** [comment]
@arsenovic is this making more sense ? I am ready to explain as many things in detail as you want. Perhaps a gitter session would help also.

**Comment by p3trus** [comment]
Haven't had the time to join the discussions yet. I have some questions
- Are the oscillator subsystems of the generic and specialized lockin merged or overwritten?
- Is both possible?
- Are multiple levels of  hirarchy possible?
- Is there an easy way to modify a feature instead of completely overwriting it? Sometimes one just needs to change some limits.
- Are the context managers neccessary or just syntactic sugar to get indentation?

**Comment by MatthieuDartiailh** [comment]
- The oscillator of the specialized lock-in is a subclass of the one of the generic lock-in. Additional base classes can be specified to allow the use of mixin classes. For the time being you can't just get rid of of the generic lock-in ocillator base class but we could add such an option.
- Multiple level of hierarchy are definitively possible.
- You can lightly alter a existing feature by using the set_feat object (see the specialized lock-in frequency).
- The context manger is just syntactic sugar to get the indentation and have a shorter name (rewritting oscillator every time would be a bit annoying and less clear IMHO)

**Comment by MatthieuDartiailh** [comment]
Happy to see you join the discussion. If you want also to join the organization let us know.

**Comment by arsenovic** [comment]
yeah the use of the context manager kind of  threw me, but i see now. 

 i dont quite follow the `@o` decorator

i joined the gitter, so you could respond on that if you like,

**Comment by MatthieuDartiailh** [comment]
I started to answer on gitter but as I am not sure I was completely clear (and as the question might pop up again), here are the rationals behind the use of the decorator.

When declaring a (let's say) _post_get_\* method which should apply to one feature of a subpart, the method needs to be stored on the subpart to be added to the runtime class which will be created from it. Also you don't want it crowding your main driver namespace as it might conflict with some feature defined on it. Something that would be quite close in term of code would be this : 

``` python
with oscillator as o:
    def _post_get_frequency(self, instance, value):
        # do stuff

    o._post_get_frequency = _post_get_frequency
    del _post_get_frequency # Not even sure this would truly work

```

This is awfully verbose as you need to name twice the method. The decorator handle for you the storing on the subpart and return a dummy object that the metaclass knows it should discard. Hope this clarifies the magic.

**Comment by arsenovic** [comment]
got it thanks!

**Comment by MatthieuDartiailh** [comment]
I just opened https://github.com/LabPy/lantz_core/pull/1 which implements this proposal. You should mainly look at has_features module as everything else is not directly related (but required to test and get a better idea of what the general structure might looks like).

**Comment by hgrecco** [comment]
@MatthieuDartiailh Great. I would look at it.

**Comment by MatthieuDartiailh** [comment]
https://github.com/LabPy/lantz_core/pull/1 has been merged so closing.
