### ISSUE TITLE
Looking to open source our in house automation solution

### ISSUE THREAD

**Issue by pazzarpj** [LabPy/labpy-discussion#20]
Hi all,
I have been working on a framework for the past few years internally at my workplace.
This library operates on a different layer than what is discussed here.
It is for sequencing tests, reporting results and setting up test criteria and user interaction.
It born out of our frustration with NI's labview and Test Stand.
I'm currently in talks within the company for embracing open sourcing for this framework.

We currently have 5 fully automated test systems and about 15 semi-automated and user prompted testing of our printed circuit assemblies and final products.

I am asking here because I saw some discussion on a python-ivi issue (that started this community) about conforming to a standard for drivers and an overview for how this community should be shaped with different libraries servicing different layers in the hierarchy.

I wanted to check here first to see if the community was active and if I should start the refactor on my own drivers that I've written with PyVisa with the alternatives suggested here as part of the open sourcing process and conforming to this community to increase acceptance.

**Comment by MatthieuDartiailh** [comment]
Hi,

I am sad to say that Labpy as a community kind of never worked and never reach the point at which driver standardization was discussed in depth. I keep working on a similar project, but my time is limited. I am however very interested in automated testing, mainly for driver validation and would be very curious to have a look at your framework
So if you look at open-sourcing your framework I would not bother in re-writing your driver as a first step. 

If you have more questions please do not hesitate, I will try to answer as fast as possible.

Best regards

**Comment by pazzarpj** [comment]
Thanks Matt for the response.
As I said before, the framework is well used.
It does have a few cobwebs as it has been a WIP since I was a beginner. It will need to modularize in order to open source as it is very tied into our systems currently.

For example; the script usually starts by prompting for serial number and validates against our standard convention. 
Program the micro controller with svn tagged image file which it will manipulate to stuff in things like serial number, CRCs, MAC addresses etc.
It will then execute tests using the fluke 8846a, rigol or Agilent funcgen,  Agilent scope,  NI DAQ, custom relay switching serial shifted hardware controlled by ftdi and/or DAQ. 
Dumps all the test criteria and results into CSVs automatically as human readable and machine parsable.

So while the batteries included set up is very nice for us, I will need to make all my systems default plugins or at least much more configurable.

**Comment by bilderbuchi** [comment]
Personally, I see this part as the most interesting (and not covered too much by other solutions)
> It is for sequencing tests, reporting results and setting up test criteria and user interaction.

From what you say, it seems it would have to be reworked quite heavily to be generally usable and flexible. Would probably best if it would concentrate on a good framework for defining sequences of steps, with decision/acceptance criteria. 
I have implemented something like this with basically a self-made state machine in the past. Also, I have once had good experience with using the testing framework pytest to run tests on an electronic device, with defined pass/fail criteria, with some plugin-provided output, etc. It was actually pretty neat, you could even prompt the user to change the hardware configuration for a subset of the tests (using fixtures). :-D

**Comment by pazzarpj** [comment]
Hey bilderbuchi.
I actually started the process for open sourcing.
Then i had twin boys. Just starting to dedicate time again after a haitus and work has committed to using the open source version of the framework for the next project with a plan to port the scripts over in the future.

Our plan is just getting it working in the open source space for our own. Then start the process of adding features like a driver manager than can use any drivers and use them in a consistent way (you can do this anyway, its just not included).

The documentation is non-existent at this stage, hence the first thing on my list for open sourcing. Also bringing it up to date to our internal database.

If you can look past that, well you can have a sneak peak of the project before culling unused code and documenting how to use the sucker.

https://github.com/pazzarpj/Fixate

**Comment by bilderbuchi** [comment]
I have already spotted this repo in the meantime. Ha, children, I know your situation well. :-D 
Don't feel pressured to anything, currently I feel like there are too many (overspecific, half-finished, not-generally-usable) solutions out there, with many folks just doing their own thing. Getting a common thing going will be lots of work...
