### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#4]
I need personally python 2 support. So I would say 2.7 and >3.2. So we must use a compatibility layer. We have two main possibilities : 
- six : used by numpy and friends
- futures : which I personally find nicer and allow to write it seems to me code closer to python 3 only code.

**Comment by hgrecco** [comment]
I would really like to drop Python 2.7 support but I think that there still a few packages which has not been ported and part of the community was not able to move to 3.2. So I would say that 2.7 & 3.2+ is fine.

+1 for futures and for code as close as possible to Python 3.

I would strongly suggest against 2to3. Also against using some optimisations that makes the code more difficult to read when these optimisations are not really necessary. For example using `future.utils.iteritems`or `future.utils.viewitems` for small dicts.

**Comment by alexforencich** [comment]
My opinion is no 2to3 and no six.  I see no reason to avoid using futures since it's built in to python.  There are still a lot of people out there using python 2, unfortunately, so I think we're stuck with being able to run on it.  I personally don't even use futures in python-ivi, but that is perhaps a little extreme.

**Comment by MatthieuDartiailh** [comment]
Actually future is not **future** so it is not built-in and we need a compatibility layer for metaclasses at least.

**Comment by MatthieuDartiailh** [comment]
Meant '__future__'

**Comment by MatthieuDartiailh** [comment]
I do agree with @hgrecco about pointless optimizations.

**Comment by MatthieuDartiailh** [comment]
@alexforencich here is a link to future documentation. Let us know what you think. http://python-future.org/

**Comment by alexforencich** [comment]
Well, if we have to use something, then the option with the least impact seems like the best one.  2to3 is a translation of sorts as far as I know, so this should probably be avoided.  So between six and future, I would go with whichever one is cleaner.

**Comment by MatthieuDartiailh** [comment]
I think future is a bit cleaner. So if everybody is fine with those decisions, I propose to close that issue and update the wiki in consequence. @hgrecco, @alexforencich, @arsenovic is that fine with you ?

**Comment by alexforencich** [comment]
Sounds like a plan.

**Comment by hgrecco** [comment]
It is fine for me.

**Comment by arsenovic** [comment]
i dont have any experience with python3, so ill deffer to you all

**Comment by MatthieuDartiailh** [comment]
Ok then I close and update the wiki.

**Comment by MatthieuDartiailh** [comment]
Contributing page of the wiki updated.
