### ISSUE TITLE
Style guides

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#6]
As we are going to be several contributors we should decide on some coding style standard. My idea would be to follow PEP8. Some part of can be annoying so we should discuss what we choose to apply and add testing for it (the vispy project is doing so actually).

**Comment by hgrecco** [comment]
+1 on PEP8

I would suggest that we also select a documentation syntax. For historical reasons I was using sphinx type, but NumPy seems to work really nice as well now with documentation generators and is cleaner.

**Comment by MatthieuDartiailh** [comment]
+1 for numpy docstrings !

**Comment by arsenovic** [comment]
+1 numpy-style

**Comment by alexforencich** [comment]
+1 on PEP8 and numpy style as well.

**Comment by MatthieuDartiailh** [comment]
As we all agree, I close this and I will update the wiki shortly.

**Comment by MatthieuDartiailh** [comment]
Wiki updated. We should also consider adding tests for PEP8 rules at some point.

**Comment by MatthieuDartiailh** [comment]
I take the liberty to re-open to discuss a minor point : the header of our files. I found some posts saying it was to be avoided to have copyright/author statements in the modules docstrings and used that kind of header : 

``` python
# -----------------------------------------------------------------------------
# Copyright 2015 by Eapii Authors, see AUTHORS for more details.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENCE, distributed with this software.
# -----------------------------------------------------------------------------
```

on the other hand @hgrecco (following the poocoo team) put that kind of things in the docstrings : 

``` python
"""
    lantz.errors
    ~~~~~~~~~~~~

    Implements base classes for instrumentation related exceptions. They are
    useful to mix with specific exceptions from libraries or modules and
    therefore allowing code to catch them via lantz excepts without
    breaking specific ones.

    :copyright: 2015 by The Lantz Authors
    :license: BSD, see LICENSE for more details.
"""
```

We should agree on one format.

**Comment by MatthieuDartiailh** [comment]
Any comments on this ? It would be better to agree sooner rather than later so that we don't have to change all the headers. @LabPy/owners

**Comment by MatthieuDartiailh** [comment]
As nobody commented let's say we follow the Pocoo team.
