### ISSUE TITLE
Lantz Action

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#7]
Lantz a special decorator for method named Action. It can do some fancy stuff like altering arguments or the like. I do see the points for units let's say but could we just use pint.wrap. ( will create an issue about unit handling) So what are your opinions ?

**Comment by hgrecco** [comment]
Action also does something else which is register the method as something instrument related. This allows you to autogenerate docs and GUIs a little bit smarter.

**Comment by MatthieuDartiailh** [comment]
I do agree about the GUI. Actually if we end up with some kind of optional unit support we might need to wrap around pint standard decorator. So I say we keep it but don't provide pre_call post_call hooks.

**Comment by MatthieuDartiailh** [comment]
While starting to write drivers I started using Action so I think it is a good time to discuss more in details
what we expect from it, whether we use a unique class or subclasses, etc...
Unit handling seems logic at least to handle the case in which Pint is not present. What else could we have ? Perhaps a byte converter for read_only byte (such as status byte), but as this is very specific perhaps a subclass would be better to avoid the base class to explode.

**Comment by hgrecco** [comment]
I think is better to keep it as small as possible. Unit handling and not much more. 

Maybe we can provide an example showing how it is done for specific cases. For example if a particular driver needs certain type of conversions all the time the user can write a specifc `MyAction` that is able to do it. We only need to provide a good example.

**Comment by MatthieuDartiailh** [comment]
I am fine with that. I will then create a util.py module to store useful function (such as byte conversion and use it in Register and in the body of Action when needed). So lets say we have something like a preprocess method which get all arguments, a postprocess method which get all return values and both do nothing but handling units and users are free to subclass Action.

**Comment by hgrecco** [comment]
Sound great.

**Comment by MatthieuDartiailh** [comment]
Actually doing it that way would prevent using the wraps method of the UnitRegistry which would be a pity. I will try to come up with something better, I think that it will always seem a bit artificial to use it on all methods but it is worth it.

**Comment by MatthieuDartiailh** [comment]
Implementation proposed in https://github.com/LabPy/lantz_core/pull/9

**Comment by MatthieuDartiailh** [comment]
Closed by https://github.com/LabPy/lantz_core/pull/9
